ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL;

ALTER TABLE tasks ADD COLUMN user_id INTEGER;

ALTER TABLE tasks ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE tasks
ADD CONSTRAINT fk_tasks_user
FOREIGN KEY (user_id)
REFERENCES users (id)
ON DELETE CASCADE;